version: "3.9"

services:
  mariadb: 
    build: ./requirements/mariadb
  nginx:
    build: ./requirements/nginx
  wordpress:
    build: ./requirements/wordpress
volumes:
  db_data: {}
  wordpress_data: {}
