version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb/
    networks:
      - inception-net
    volumes:
      - db_data:/var/lib/mysql/data
    restart: on-failure
  nginx:
    build: ./requirements/nginx/
    networks:
      - inception-net
    ports:
      - "80:80"
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress/
    networks:
      - inception-net
    restart: on-failure
volumes:
  db_data: {}
  wordpress_data: {}

networks:
  inception-net:
